### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by daraghbroderick** [raspberrypilearning/scouts-do-it-pass-it#1]
Hey great project, this will be really fun!
Here are the small few things I noticed when trying it out.

- [ ] Explicitly instruct learners to name the variable 'action' at the beginning or bold/highlight the word **action**. Just to make sure they don't name it something different and struggle with following the code later. 
- [ ] Code for step 2 of 'Light!' Section still has pick random 1 to 3 but now has four actions.
- [ ] Image broken on 'Light!' Section - step that starts with: The light level…

**Comment by tracygardner** [comment]
All feedback addressed. Thanks @daraghbroderick
